#Config File for iRestore
#A Minecraft/Bukkit plugin made by triarry
#
#DO NOT CHANGE THIS LINE
version: 2.1

#triarry's github: https://github.com/triarry/iRestore
#

death-message: true
keep-inventory: true
keep-xp: true
xp-to-remove: 0
my-pet-enabled: false
heroes-enabled: false
check-for-updates: true
events:
    other:
        all: false
        anvil: false
        cactus: false
        drowning: false
        enderpearl: false
        falling: false
        fire: false
        lava: false
        lightning: false
        starvation: false
        suffocation: false
        suicide: false
        tnt: false
        void: false
    mobs:
        all: false
        angry_wolf: false
        baby_zombie: false
        blaze: false
        cave_spider: false
        creeper: false
        enderdragon: false
        enderman: false
        ghast: false
        giant: false
        iron_golem: false
        magma_cube: false
        silverfish: false
        skeleton: false
        slime: false
        spider: false
        witch: false
        wither: false
        wither_skeleton: false
        zombie: false
        zombie_pigman: false
        zombie_villager: false
    pvp:
        all: true
        bows: false
        melee: false
        potions: false
        tamed_wolf: false
        tnt: false
        skills: false
vault:
    enabled: false
    money-to-steal: 2
blacklist:
    enabled: false
    items:
    - 144
    - 397
whitelist:
    enabled: false
    items:
    - 299
    - 300
percentage-drop:
    enabled: false
    percentage: 50